Update R8 to fix `NoSuchMethodError` crash (mihonapp/mihon#914)
(cherry picked from commit f3226fb278cab87422255e04e647c50095b61529)

Fix R8 version configuration not working (mihonapp/mihon#916)

This reverts commit f3226fb278cab87422255e04e647c50095b61529.

(cherry picked from commit 4182ae89a036525c5575961a68371df249ce384f)